### ISSUE TITLE
Great code

### ISSUE THREAD

**Issue by zavloc** [jindw/xmldom#270]
Thanks

**Comment by karfau** [comment]
Hey there, I just want to let you know that I disagree ... to some degree.

I mean back when I started investing time into maintaining a fork of this project at https://github.com/xmldom/xmldom, I think I also partially did it for some interrsting ideas for how this code is structured and the impressiveness of what this code is able to achieve.

But wow, little did I know what a maintainable mess this code base was, or actually still is, even in the fork.
Not just that the version in this repo has several security vulnerabilities that have been fixed in the fork.
The code for parsing is such spaghetti code and so hard to follow for how it actually deals with the absurd complexity of XML (and attemps to treat HTML as "similar enough" to try and do both if it, spoiler alert: it only works to some degree).
And just from how the code in this repository is "tested" and setup is no longer "state of the art".

Last but not least, nowadays there are many better option for the capabilities this lib offers.

**Comment by zavloc** [comment]
Thanks for the tip.

And my first message was somewhat sarcastic, but I understand that it is
his job and that not reading every detail of a contract by a user makes him
responsible for his own use.

What worries me the most is that I don't think that only one user has these
"problems" with the conditions and terms. In addition, I don't think it's
limited to just one operating system.

So my interest in learning to program is genuine, since I now realize how
late we are in Mexico in the development of daily life and education (and
other poorer countries must be worse).

From your message I understand that you are a good person, I also
understand that certain "government regulations" of certain users are
needed for certain activities they carry out (with or without their
consent) since it is legally enough that they are accepted from a "verified
account". What I want to convey to you is that sometimes it can "be
justified", although that does not mean that by not knowing how to read or
not having that culture of getting informed some users can reach the edge
of madness, loneliness, isolation and a mental breakdown from which some no
longer return.

I don't know where I am, what I do know is that I must learn what in the
"modern world" is done every day. Unfortunately there are other people who
due to lack of resources and access to education (propitiated by the
government itself), but not due to lack of interest; they have not been
able to take their time to read, which has caused them not to return from
that mental breakdown.

My point is that those limitations must be removed quickly and gradually
advance in global education (without economic purposes), rather with a view
to global social and educational purposes with access to all. Otherwise, I
don't know whether to be more afraid of climate change or social madness
(although strictly climate change has also been caused by this same lack of
social humanity and the search for individual wealth).

I appreciate your attention and I apologize for taking so long to respond,
but I am years away from learning what you know. So I will follow my path
at my own pace; and just like you, I hope that there are more developers of
good morals and that in some way they can help reduce these "galts" of time
in the learning and transmission of information.

Thank you and have a nice night.

**Comment by karfau** [comment]
While your first "sarcastic" comment/issue (also being your first issue at all), was surely done by using GitHub from the browser, your reply looks like you replied to the mail that GitHub send to you as a notification.
Since it looks like you are(/your account is) new to GitHub, you might not be aware that this ends up as a reply in this issue, so I want to make sure you are aware of it and can consider your options of hiding or even deleting it. At least I hope this is possible for the comments you add in repositories not owned by you.

Not saying that you should delete it, just making you aware of your options.

I can imagine how the feeling of "lagging behind" on the personal or even systemical level can feel devastating/discouraging, especially at a point in time where OSS is facing major trust issues due to "bad actors" playing "long term phsycological attacs" in order to take over trusted projects before putting hidden malicious code into them.
I would still say there is (a lot of hope) even for new people since the OSS community is still providing tons of differently sized opportunities to learn and engage and I would say "generally appreciates new perspectives".
(If you stumble over a project in which this is not the case, go find another one, there are so many options!)

That being said.
Communication is key, especially bring humble.
So starting a conversation with sarcasm without making it explicit or also being constructive might already be a reason for some people to not even reply.

I wish you a pleasant and sustainable journey and learning path into programming/OSS.
