### ISSUE TITLE
document.firstChild returns XML Declaration

### ISSUE THREAD

**Issue by anttileppa** [jindw/xmldom#83]
document.firstChild returns xml decoration instead of first child child node.

**Comment by reidrankin** [comment]
I recently ran into this issue myself with an upstream dependency on xmldom. I just wanted to clarify what's going on for anyone who comes looking, because it took me a while to get it straight.

The XML DOM Level 2 standard [specifies](https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-1590626202) that, far from simply containing a single Element node, a Document node may have 4 different types of children: an Element node (once), a DocumentType node (once), (potentially multiple) ProcessingInstruction nodes, and (potentially multiple) Comment nodes, all in no particular order. Using document.firstChild may get any of these. The appropriate method of accessing the root element in the document is document.documentElement.

This also means that PR #84 does not go far enough to achieve its desired behavior: you'd need to skip Comment and DocumentType nodes too.
